import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Earlymark",
  description: "How Earlymark AI collects, uses, and protects your data.",
};

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-muted-foreground">Last Updated: April 2026</p>

      <h2>1. Introduction and Acceptance</h2>
      <p>
        This Privacy Policy (<strong>"Policy"</strong>) governs the collection, use, storage, disclosure, and
        handling of personal information by Earlymark AI Pty Ltd (<strong>"Earlymark AI"</strong>,{" "}
        <strong>"we"</strong>, <strong>"us"</strong>, or <strong>"our"</strong>) in connection with the
        Earlymark AI platform and all associated services (<strong>"Platform"</strong>).
      </p>
      <p>
        <strong>
          By accessing or using the Platform in any way, you confirm that you have read, understood, and
          agree to be bound by this Policy in its entirety. If you do not agree to this Policy, you must
          immediately cease using the Platform.
        </strong>
      </p>
      <p>
        Earlymark AI reserves the right to modify this Policy at any time without prior notice by posting
        an updated version on this page. Changes take effect immediately upon posting. Your continued use
        of the Platform after any modification constitutes your unconditional acceptance of the revised
        Policy. You are solely responsible for reviewing this page periodically to remain informed of
        any changes.
      </p>

      <h2>2. About Earlymark AI (Data Controller)</h2>
      <p>
        Earlymark AI Pty Ltd is the data controller for all personal information collected through the
        Platform. We are an Australian company operating under Australian law.
      </p>
      <p>
        Privacy enquiries and data rights requests should be directed to our Privacy Officer at:{" "}
        <a href="mailto:privacy@earlymark.ai">privacy@earlymark.ai</a>
      </p>

      <h2>3. Data We Collect</h2>
      <p>
        Earlymark AI collects personal and non-personal information through your use of the Platform.
        Categories of data we collect include:
      </p>
      <ul>
        <li>
          <strong>Identity data:</strong> Full name, email address, phone number, Australian Business
          Number (ABN) or Australian Company Number (ACN), and other identifying information you provide.
        </li>
        <li>
          <strong>Job and commercial data:</strong> Job descriptions, site addresses, schedules, quotes,
          invoices, photos, client records, and related business records entered into or generated by
          the Platform.
        </li>
        <li>
          <strong>Financial data:</strong> Payment method details, billing address, subscription history,
          and transaction records processed via Stripe and Xero.
        </li>
        <li>
          <strong>Communications data:</strong> SMS message content, voice call recordings, call
          transcripts, and AI-assisted conversation logs generated through the Platform.
        </li>
        <li>
          <strong>Usage and device data:</strong> IP addresses, browser type and version, device
          identifiers, operating system, referring URLs, feature usage patterns, click paths, and
          session logs.
        </li>
        <li>
          <strong>AI-inferred data:</strong> Data derived by AI models from the above, including
          predicted lead quality scores, customer sentiment assessments, job likelihood estimates,
          and behavioural patterns.
        </li>
      </ul>
      <p>
        You are responsible for ensuring that any personal information you enter into the Platform
        about third parties (including your customers) has been collected lawfully and that those
        individuals have been informed of its use. Earlymark AI accepts no liability for unlawful
        data collection by users.
      </p>

      <h2>4. Lawful Basis and Consent</h2>
      <p>
        Earlymark AI processes personal information on the following lawful bases under the Australian
        Privacy Act 1988 and applicable Australian Privacy Principles (APPs):
      </p>
      <ul>
        <li>
          <strong>Contractual necessity:</strong> Processing required to provide, maintain, and improve
          the services you have subscribed to.
        </li>
        <li>
          <strong>Legitimate business interest:</strong> Security monitoring, fraud prevention, internal
          analytics, product development, and aggregated benchmarking.
        </li>
        <li>
          <strong>Legal obligation:</strong> Compliance with Australian tax law, financial record-keeping
          requirements, and regulatory obligations.
        </li>
        <li>
          <strong>Consent:</strong> Consent is implied by your continued use of the Platform. Withdrawal
          of consent requires closure of your account. Partial withdrawal of consent is not available
          where the processing is necessary for service delivery.
        </li>
      </ul>

      <h2>5. How We Use Your Data</h2>
      <p>Earlymark AI uses collected data for the following purposes:</p>
      <ul>
        <li>Providing, operating, and maintaining the Platform and all its features.</li>
        <li>Processing payments, managing billing, and preventing fraud.</li>
        <li>Delivering AI-assisted communications, scheduling, quoting, and reporting.</li>
        <li>Security monitoring, incident detection, and access control.</li>
        <li>
          Internal analytics and product improvement, including using de-identified and aggregated
          data to train, test, and improve Earlymark AI's internal models, algorithms, and features.
        </li>
        <li>
          Marketing communications to existing users regarding new features or services offered by
          Earlymark AI. You may opt out of marketing communications at any time by contacting{" "}
          <a href="mailto:privacy@earlymark.ai">privacy@earlymark.ai</a>.
        </li>
        <li>Complying with legal obligations and responding to lawful government requests.</li>
        <li>
          Facilitating corporate transactions including mergers, acquisitions, restructurings, and
          asset sales (see Section 9).
        </li>
      </ul>

      <h2>6. AI and Automated Processing</h2>
      <p>
        The Platform uses artificial intelligence, including Google Gemini, to automate communications,
        scheduling, quoting, and customer interactions. Your data — including job details, customer
        information, and conversation history — is processed by these AI models to generate outputs.
      </p>
      <p>
        <strong>
          Earlymark AI makes no representation or warranty, express or implied, that AI-generated
          outputs are accurate, complete, current, fit for any particular purpose, or suitable for
          reliance. The subscribing business is solely responsible for reviewing and approving all
          AI-generated content — including quotes, messages, schedules, and invoices — before acting
          on it or sending it to customers.
        </strong>
      </p>
      <p>
        Earlymark AI accepts no liability whatsoever for any loss, damage, cost, or claim arising from
        reliance on AI-generated outputs, including but not limited to inaccurate pricing, missed
        appointments, or miscommunicated commitments.
      </p>
      <p>
        AI conversation logs are retained for up to 90 days. Google Gemini processes data under
        Google's applicable Data Processing Agreement. Earlymark AI is not responsible for Google's
        data handling practices.
      </p>

      <h2>7. Aggregated and De-identified Data</h2>
      <p>
        Earlymark AI may aggregate and de-identify personal information such that it can no longer
        reasonably be used to identify an individual. Such aggregated or de-identified data does not
        constitute personal information under the Australian Privacy Act 1988.
      </p>
      <p>
        Earlymark AI retains the right to use aggregated and de-identified data freely, without
        restriction and without time limit, including after your account is closed, for any lawful
        purpose including analytics, industry benchmarking, model improvement, feature development,
        and publication of insights. No compensation is payable to you for such use.
      </p>

      <h2>8. Third-Party Sub-Processors</h2>
      <p>
        Earlymark AI shares the minimum data necessary with the following sub-processors to deliver
        platform functionality. By using the Platform, you accept the privacy policies and terms of
        each sub-processor as a condition of use.
      </p>
      <table>
        <thead>
          <tr>
            <th>Provider</th>
            <th>Purpose</th>
            <th>Data shared</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Supabase</strong></td>
            <td>Database and storage (Australia region)</td>
            <td>All platform data</td>
          </tr>
          <tr>
            <td><strong>Twilio</strong></td>
            <td>SMS and voice communications</td>
            <td>Phone numbers, message content</td>
          </tr>
          <tr>
            <td><strong>LiveKit</strong></td>
            <td>WebRTC voice infrastructure</td>
            <td>Call audio streams</td>
          </tr>
          <tr>
            <td><strong>Google (Gemini / Maps)</strong></td>
            <td>AI processing and location verification</td>
            <td>Conversation context, addresses</td>
          </tr>
          <tr>
            <td><strong>Xero</strong></td>
            <td>Accounting and invoicing</td>
            <td>Financial records, client details</td>
          </tr>
          <tr>
            <td><strong>Stripe</strong></td>
            <td>Payment processing</td>
            <td>Payment method and transaction data</td>
          </tr>
        </tbody>
      </table>
      <p>
        Earlymark AI is not responsible for the data handling, security practices, or privacy
        compliance of any sub-processor. Earlymark AI accepts no liability for any breach, loss,
        or misuse of data by any third-party provider.
      </p>

      <h2>9. Business Transfers</h2>
      <p>
        In the event of a merger, acquisition, asset sale, restructuring, insolvency, or other
        corporate transaction involving Earlymark AI, user data — including personal information —
        may be transferred to the acquiring or successor entity as part of that transaction,
        <strong> without notice to or separate consent from affected users.</strong>
      </p>
      <p>
        Following any such transfer, your personal information will remain subject to the privacy
        policy then in effect. Earlymark AI will notify affected users post-transfer only where
        required to do so by applicable law.
      </p>

      <h2>10. Data Retention</h2>
      <p>
        Earlymark AI retains personal data for as long as necessary to provide the Platform and
        satisfy applicable legal, regulatory, and financial obligations. The following minimum
        retention periods apply:
      </p>
      <table>
        <thead>
          <tr>
            <th>Data type</th>
            <th>Retention period</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Contact and job records</td>
            <td>Life of account + 2 years</td>
          </tr>
          <tr>
            <td>Financial records (invoices, payments)</td>
            <td>7 years (Australian tax law)</td>
          </tr>
          <tr>
            <td>AI conversation logs</td>
            <td>90 days</td>
          </tr>
          <tr>
            <td>Security and access logs</td>
            <td>12 months</td>
          </tr>
          <tr>
            <td>Deleted account personal data</td>
            <td>Up to 90 days, then purged</td>
          </tr>
          <tr>
            <td>Aggregated / de-identified data</td>
            <td>Indefinitely</td>
          </tr>
        </tbody>
      </table>
      <p>
        Earlymark AI may retain data beyond these periods where required by law, subject to an
        active legal hold, or where the data has been aggregated and de-identified.
      </p>

      <h2>11. Security</h2>
      <p>
        Earlymark AI implements reasonable technical and organisational security measures, including:
      </p>
      <ul>
        <li>AES-256-GCM encryption for data at rest, including OAuth tokens and sensitive credentials.</li>
        <li>TLS encryption for all data in transit between users and the Platform.</li>
        <li>Role-based access controls limiting data access to authorised personnel and systems.</li>
        <li>Audit logging of sensitive operations and privileged access events.</li>
        <li>Automated secret scanning and continuous security monitoring.</li>
      </ul>
      <p>
        <strong>
          No data transmission over the internet or method of electronic storage is 100% secure.
          Earlymark AI does not warrant that the Platform will be free from unauthorised access,
          cyberattack, or data loss.
        </strong>{" "}
        Earlymark AI is not liable for security breaches outside its reasonable control, including
        those caused by user negligence (such as weak passwords or credential sharing), third-party
        provider failures, or events beyond Earlymark AI's reasonable control.
      </p>

      <h2>12. Your Rights (Australian Privacy Act 1988)</h2>
      <p>
        Your rights in relation to personal information held by Earlymark AI are governed exclusively
        by the Australian Privacy Act 1988 and the Australian Privacy Principles (APPs). These rights are:
      </p>
      <ul>
        <li>
          <strong>Right of access (APP 12):</strong> You may request access to personal information
          Earlymark AI holds about you. We will respond within 30 days and may charge a reasonable
          fee for access.
        </li>
        <li>
          <strong>Right to correction (APP 13):</strong> You may request correction of personal
          information that is inaccurate, out of date, incomplete, irrelevant, or misleading. We will
          respond within 30 days.
        </li>
      </ul>
      <p>
        Earlymark AI may decline an access or correction request where it would impose an unreasonable
        burden, conflict with a legal obligation, reveal confidential commercial information, or relate
        to data that has already been de-identified or purged.
      </p>
      <p>
        <strong>
          Earlymark AI does not make voluntary commitments under the EU General Data Protection
          Regulation (GDPR), the California Consumer Privacy Act (CCPA/CPRA), or any other overseas
          privacy framework, except where strictly required by applicable law.
        </strong>
      </p>
      <p>
        To submit a request, contact{" "}
        <a href="mailto:privacy@earlymark.ai">privacy@earlymark.ai</a>.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, <strong>Earlymark AI's total cumulative
        liability</strong> arising out of or related to this Policy, your data, or your use of the
        Platform — whether in contract, tort (including negligence), statute, or otherwise — is
        capped at the <strong>greater of AUD $100 or the total fees paid by you in the 30 days
        immediately preceding the event giving rise to the claim.</strong>
      </p>
      <p>Earlymark AI expressly excludes all liability for:</p>
      <ul>
        <li>Indirect, special, consequential, incidental, punitive, or exemplary loss or damage.</li>
        <li>Loss of profits, revenue, contracts, business opportunity, or goodwill.</li>
        <li>Loss, corruption, or unavailability of data.</li>
        <li>Any loss arising from reliance on AI-generated content.</li>
        <li>Service interruptions, outages, or third-party provider failures.</li>
        <li>Any breach caused by user negligence, misconfiguration, or unauthorised access.</li>
      </ul>
      <p>
        Nothing in this section purports to exclude liability that cannot lawfully be excluded under
        the Australian Consumer Law or any other non-excludable statutory guarantee.
      </p>

      <h2>14. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless Earlymark AI, its directors, officers,
        employees, contractors, and agents from and against any and all claims, demands, actions,
        losses, liabilities, damages, costs, and expenses (including reasonable legal fees) arising
        out of or in connection with:
      </p>
      <ul>
        <li>Your use or misuse of the Platform or any feature thereof.</li>
        <li>Your violation of this Policy or the Terms of Service.</li>
        <li>
          Inaccurate, incomplete, or unlawfully collected personal information you have entered into
          the Platform.
        </li>
        <li>Your reliance on AI-generated outputs without independent review.</li>
        <li>
          Any claim brought by your customers or employees arising from your use of the Platform,
          including claims related to AI-generated communications sent on your behalf.
        </li>
        <li>Your breach of any applicable privacy, consumer protection, or data protection law.</li>
      </ul>

      <h2>15. Children&apos;s Privacy</h2>
      <p>
        The Platform is intended solely for use by businesses and individuals aged 18 or over.
        Earlymark AI does not knowingly collect personal information from persons under 18 years of age.
        If we become aware that personal information has been submitted by or about a person under 18,
        we will take reasonable steps to delete it promptly.
      </p>

      <h2>16. Changes to This Policy</h2>
      <p>
        Earlymark AI may update, modify, or replace this Policy at any time by posting the revised
        version on this page. The "Last Updated" date at the top of this page will reflect the date
        of the most recent revision.
      </p>
      <p>
        <strong>
          Changes take effect immediately upon posting. Your continued use of the Platform after
          the posting of any changes constitutes your unconditional acceptance of the revised Policy.
        </strong>{" "}
        It is your responsibility to check this page regularly. Earlymark AI is under no obligation
        to provide direct notice of changes.
      </p>

      <h2>17. Governing Law and Dispute Resolution</h2>
      <p>
        This Policy and all matters arising out of or relating to it are governed exclusively by the
        laws of New South Wales, Australia, without regard to conflict of law principles.
      </p>
      <p>
        Any dispute arising from or in connection with this Policy, your data, or your use of the
        Platform is subject to the exclusive jurisdiction of the courts of New South Wales, Australia.{" "}
        <strong>You irrevocably waive any right to participate in class-action, collective,
        or representative legal proceedings</strong> against Earlymark AI in any jurisdiction.
        Where permitted by law, Earlymark AI may elect, at its sole discretion, to resolve disputes
        through binding arbitration rather than court proceedings.
      </p>

      <h2>18. Contact and Regulatory Complaints</h2>
      <p>
        For privacy enquiries, to exercise your rights under the Australian Privacy Act, or to raise a
        concern about our data handling, contact our Privacy Officer:
      </p>
      <p>
        <strong>Email:</strong>{" "}
        <a href="mailto:privacy@earlymark.ai">privacy@earlymark.ai</a>
        <br />
        <strong>Response time:</strong> Acknowledgement within 5 business days; full response within 30 days.
      </p>
      <p>
        If you are unsatisfied with our response, you may lodge a complaint with the{" "}
        <strong>Office of the Australian Information Commissioner (OAIC)</strong>:
      </p>
      <ul>
        <li>Website: <a href="https://www.oaic.gov.au" target="_blank" rel="noopener noreferrer">oaic.gov.au</a></li>
        <li>Phone: 1300 363 992</li>
      </ul>
    </article>
  );
}
