// ─── Comprehensive Tutorial Steps (185+) ────────────────────────────
// Each step spotlights a feature/button/area and shows a chat example

export interface TutorialStep {
    id: string
    targetId: string | null
    title: string
    message: string
    chatExample?: { input: string; output: string }
    position?: string
    actionLabel: string
    section?: string
}

export const TUTORIAL_STEPS: TutorialStep[] = [
    // ══════════════════════════════════════════════════════════════
    // SECTION 1: WELCOME & INTRO (Steps 1-5)
    // ══════════════════════════════════════════════════════════════
    { id: "welcome", targetId: null, title: "Welcome to Pj Buddy! 🎉", message: "I'm Pj, your AI business assistant. My goal is to handle the heavy lifting so you can focus on the tools, not the tech. Let's take a quick tour!", actionLabel: "Let's Go", section: "Welcome" },
    { id: "chat-first", targetId: null, title: "💬 Just Chat — That's It!", message: "The EASIEST way to use Pj Buddy is to just talk to me.\n\n📱 Type: \"New job for John Smith\"\n📱 Type: \"Show stale deals\"\n📱 Type: \"Send a quote for $500\"\n\nI'll understand exactly what you mean.", actionLabel: "Cool!" },
    { id: "ai-philosophy", targetId: null, title: "🧠 How I Think", message: "I use fuzzy matching — so even if you type 'Sparkie' I know you mean Electrician, and 'Syndey' means Sydney. I learn your preferences over time and remember your rules.", actionLabel: "Nice!" },
    { id: "two-modes", targetId: null, title: "Two Modes, One App", message: "Pj Buddy has two viewing modes:\n\n🟢 Basic Mode — Clean chat interface, no clutter\n🔵 Advanced Mode — Full dashboard with pipeline, map, reports\n\nYou can switch anytime!", actionLabel: "Got it" },
    { id: "lets-explore", targetId: null, title: "Let's Explore! 🗺️", message: "I'll now walk you through every feature. Each step will spotlight the relevant button or area. The chatbox on the right shows what you can TYPE instead of clicking.", actionLabel: "Show me" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2: BASIC MODE & CHAT (Steps 6-20)
    // ══════════════════════════════════════════════════════════════
    { id: "basic-mode", targetId: "assistant-pane", title: "Basic Mode — Your AI Companion", message: "This is where the magic happens. Basic Mode hides complex widgets, leaving you with an intelligent chat.", chatExample: { input: "What's on today?", output: "You have 3 jobs scheduled: 9am Plumbing at Smith's, 11am Electrical at Jones, 2pm HVAC service." }, position: "left", actionLabel: "Next", section: "Basic Mode" },
    { id: "voice-input", targetId: "voice-btn", title: "🎙️ Voice Commands", message: "Dirty hands? Click the microphone to dictate. I'll translate your voice into action.", chatExample: { input: "🎤 \"New job for Mary, blocked drain, tomorrow 2pm\"", output: "Job created: Blocked Drain for Mary, scheduled tomorrow 2pm." }, position: "left", actionLabel: "Next" },
    { id: "chat-input", targetId: "chat-input", title: "💬 The Command Line", message: "Type anything here. Create jobs, send texts, check your schedule — all in plain English.", chatExample: { input: "Text Steven I'm on my way", output: "SMS sent to Steven: \"I'm on my way!\"" }, position: "left", actionLabel: "Next" },
    { id: "chat-create-job", targetId: "chat-input", title: "Create a Job via Chat", message: "Just describe the job naturally. I'll parse the client, work, price, time and address.", chatExample: { input: "New repair job for Frank at 300 George St for $600 tomorrow 2pm", output: "Job \"Repair\" created for Frank at 300 George St, $600, scheduled tomorrow 2pm." }, position: "left", actionLabel: "Next" },
    { id: "chat-move-deal", targetId: "chat-input", title: "Move Deals via Chat", message: "Drag and drop is great, but typing is faster.", chatExample: { input: "Move John's deal to completed", output: "Done! \"Kitchen Reno\" moved to Completed." }, position: "left", actionLabel: "Next" },
    { id: "chat-stale", targetId: "chat-input", title: "Find Stale Deals", message: "I'll flag deals that haven't moved in 7+ days.", chatExample: { input: "Show stale jobs", output: "2 jobs need attention:\n! Deck Build ($8,500) — 9d\n!! Plumbing Fix ($4,500) — 16d" }, position: "left", actionLabel: "Next" },
    { id: "chat-schedule", targetId: "chat-input", title: "Check Your Schedule", message: "Ask me about your availability any time.", chatExample: { input: "What jobs do I have tomorrow?", output: "Tomorrow you have 2 jobs:\n9am — Smith Plumbing ($450)\n2pm — Jones Electrical ($800)" }, position: "left", actionLabel: "Next" },
    { id: "chat-invoice", targetId: "chat-input", title: "Quick Invoicing", message: "Generate invoices with a single command.", chatExample: { input: "Invoice Deck Build for $8,500", output: "Invoice INV-042 generated for Deck Build — $8,500. Deal moved to Invoiced." }, position: "left", actionLabel: "Next" },
    { id: "chat-sms", targetId: "chat-input", title: "Send SMS via Chat", message: "Text clients without leaving the app.", chatExample: { input: "Text Wendy I'll be there in 15 mins", output: "SMS sent to Wendy: \"I'll be there in 15 mins\"" }, position: "left", actionLabel: "Next" },
    { id: "chat-email", targetId: "chat-input", title: "Send Emails via Chat", message: "Draft and send emails to clients.", chatExample: { input: "Email John about the delayed parts", output: "Email sent to John: Subject \"Parts Update\" — explaining the delay." }, position: "left", actionLabel: "Next" },
    { id: "chat-call", targetId: "chat-input", title: "Make Calls via Chat", message: "Initiate calls through your AI voice agent.", chatExample: { input: "Call Mary about the quote", output: "Initiating call to Mary (0412 345 678). Purpose: follow up on quote." }, position: "left", actionLabel: "Next" },
    { id: "chat-contact", targetId: "chat-input", title: "Search Contacts", message: "Find anyone in your CRM with fuzzy search.", chatExample: { input: "Find Thompson", output: "Found: Sarah Thompson — 0412 345 678, sarah@email.com. Last job: Kitchen Reno." }, position: "left", actionLabel: "Next" },
    { id: "chat-reminder", targetId: "chat-input", title: "Set Reminders", message: "Never forget a follow-up again.", chatExample: { input: "Remind me tomorrow to order copper pipes for Sarah", output: "Reminder set: \"Order copper pipes for Sarah\" — Tomorrow 9:00 AM" }, position: "left", actionLabel: "Next" },
    { id: "chat-note", targetId: "chat-input", title: "Log Notes (Hands-Free)", message: "Perfect for on-site logging.", chatExample: { input: "Note: switchboard at Kensington is illegal, needs upgrade", output: "Note logged: \"Switchboard at Kensington is illegal, needs upgrade\"" }, position: "left", actionLabel: "Next" },
    { id: "chat-preferences", targetId: "chat-input", title: "Teach Me Your Rules", message: "I remember your preferences permanently.", chatExample: { input: "From now on always add 1 hour buffer between jobs", output: "Preference saved: \"Always add 1 hour buffer between jobs\". I'll follow this rule." }, position: "left", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3: ADVANCED MODE & DASHBOARD (Steps 21-35)
    // ══════════════════════════════════════════════════════════════
    { id: "mode-toggle", targetId: "mode-toggle-btn", title: "🔄 Toggle Advanced Mode", message: "Click this to switch between Basic (chat) and Advanced (full dashboard) modes.", chatExample: { input: "Toggle advanced mode", output: "Switched to Advanced Mode. You can now see the full dashboard." }, position: "bottom", actionLabel: "Next", section: "Advanced Mode" },
    { id: "dashboard-home", targetId: "dashboard-link", title: "🏠 The Dashboard", message: "Your morning coffee view. See your entire business at a glance.", chatExample: { input: "Give me my daily summary", output: "Today: 4 jobs, $2,400 revenue. 1 overdue task. 3 new messages." }, position: "right", actionLabel: "Next" },
    { id: "kpi-cards", targetId: "kpi-cards", title: "📊 Business Metrics", message: "Track total revenue, win rates, and pending jobs in real-time.", chatExample: { input: "How much revenue this month?", output: "February revenue: $24,500 from 18 completed jobs. Win rate: 72%." }, position: "bottom", actionLabel: "Next" },
    { id: "kpi-revenue", targetId: "kpi-cards", title: "💰 Revenue Tracking", message: "See your pipeline value, completed revenue, and outstanding invoices.", chatExample: { input: "What's my pipeline value?", output: "Current pipeline: $56,200 across 5 active jobs." }, position: "bottom", actionLabel: "Next" },
    { id: "kpi-winrate", targetId: "kpi-cards", title: "📈 Win Rate", message: "Track your quote-to-job conversion rate.", chatExample: { input: "What's my win rate this month?", output: "Quote win rate: 72% (13 won / 18 quoted)." }, position: "bottom", actionLabel: "Next" },
    { id: "search-global", targetId: "search-btn", title: "🔍 Global Search (Cmd+K)", message: "Find contacts, deals, and jobs instantly with fuzzy matching.", chatExample: { input: "Find John Doe", output: "John Doe — VIP Client. Last job: Installed Rheem HWS. Active: Kitchen Reno ($5k)." }, position: "bottom", actionLabel: "Next" },
    { id: "notifications", targetId: "notifications-btn", title: "🔔 Notifications Hub", message: "Alerts for incoming approvals, reminders, and messages.", chatExample: { input: "Show my notifications", output: "3 new: Quote approved (Smith), Reminder (order pipes), SMS from Wendy." }, position: "bottom", actionLabel: "Next" },
    { id: "new-deal-manual", targetId: "new-deal-btn", title: "➕ Manual Entry", message: "Prefer forms? Click here to create a job manually.", chatExample: { input: "Create a new contact for Mike, number 0412 345 678", output: "Contact created: Mike Stevenson — 0412 345 678." }, position: "bottom", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4: SIDEBAR NAVIGATION (Steps 36-55)
    // ══════════════════════════════════════════════════════════════
    { id: "sidebar", targetId: "sidebar-nav", title: "📋 The Command Center", message: "Your master navigation. Let's walk through every tool.", chatExample: { input: "Take me to settings", output: "Navigating to Workspace Settings..." }, position: "right", actionLabel: "Let's look", section: "Navigation" },
    { id: "nav-home", targetId: "dashboard-link", title: "1. Home Dashboard", message: "Your daily overview with KPIs, recent activity, and pipeline snapshot.", chatExample: { input: "What's on today?", output: "3 jobs: 9am Smith, 11am Jones, 2pm HVAC. Revenue today: $1,850." }, position: "right", actionLabel: "Next" },
    { id: "nav-inbox", targetId: "inbox-link", title: "2. Unified Inbox", message: "All SMS, emails, and call transcripts in one place. Reply directly from here.", chatExample: { input: "Show my texts with Steven", output: "Last 5 messages with Steven:\nYou: I'll be there at 2pm\nSteven: Great, gate code is 1234..." }, position: "right", actionLabel: "Next" },
    { id: "inbox-sms", targetId: "inbox-link", title: "Inbox: SMS Threads", message: "Client SMS replies are auto-routed here. No need to check your phone.", chatExample: { input: "What did Mary say?", output: "Mary's last message (2h ago): \"Can we reschedule to Thursday?\"" }, position: "right", actionLabel: "Next" },
    { id: "inbox-call-log", targetId: "inbox-link", title: "Inbox: Call Transcripts", message: "AI call transcripts and voicemails appear here too.", chatExample: { input: "Show my call with John", output: "Call transcript (3 min): John asked about kitchen reno timeline..." }, position: "right", actionLabel: "Next" },
    { id: "nav-schedule", targetId: "schedule-link", title: "3. Smart Schedule", message: "Visual calendar view. Jobs auto-slot when the AI creates them.", chatExample: { input: "Am I free Thursday afternoon?", output: "Thursday PM: You have a slot from 1pm-5pm available." }, position: "right", actionLabel: "Next" },
    { id: "schedule-conflict", targetId: "schedule-link", title: "Schedule: Conflict Detection", message: "I check for clashes before booking and suggest alternatives.", chatExample: { input: "Book plumbing job for Tuesday 10am", output: "⚠️ Conflict: You have Smith Electrical at 10am. Free slots: 8am or 1pm." }, position: "right", actionLabel: "Next" },
    { id: "schedule-routing", targetId: "schedule-link", title: "Schedule: Smart Routing", message: "I group nearby jobs together to minimize driving.", chatExample: { input: "Schedule Mary's job for tomorrow", output: "Booked 11am — after Jones (same suburb, 2km away). Saves 30min driving." }, position: "right", actionLabel: "Next" },
    { id: "nav-map", targetId: "map-link", title: "4. Interactive Route Map", message: "See all active jobs plotted on a live map with color-coded pins.", chatExample: { input: "Show me the map for today", output: "4 jobs plotted. Optimal route: Smith → Jones → Davis → Williams (42km)." }, position: "right", actionLabel: "Next" },
    { id: "map-pins", targetId: "map-link", title: "Map: Job Pins", message: "Blue = Scheduled, Orange = Traveling, Green = Active, Grey = Complete.", chatExample: { input: "Show nearby clients", output: "5 past clients within 3km of your location. 2 are due for service." }, position: "right", actionLabel: "Next" },
    { id: "map-navigation", targetId: "map-link", title: "Map: Navigation", message: "Launch Google Maps or Apple Maps directly from any pin.", chatExample: { input: "Get directions to next job", output: "Opening Google Maps: 42 Wallaby Way → ETA 18 mins." }, position: "right", actionLabel: "Next" },
    { id: "nav-contacts", targetId: "contacts-link", title: "5. Contact Directory", message: "Every person auto-saved to CRM. View history, phone, notes.", chatExample: { input: "What's John's phone number?", output: "John Doe: 0412 345 678 | john@email.com | VIP Client" }, position: "right", actionLabel: "Next" },
    { id: "contacts-profile", targetId: "contacts-link", title: "Contacts: Client Profiles", message: "Full history, job timeline, properties, and internal notes.", chatExample: { input: "Tell me about Jane Smith", output: "Jane Smith — Landlord. 5 properties. LTV: $15k/year. Last job: 3 weeks ago." }, position: "right", actionLabel: "Next" },
    { id: "contacts-properties", targetId: "contacts-link", title: "Contacts: Multi-Property", message: "Landlords with multiple properties? Track each one.", chatExample: { input: "Show Jane's properties", output: "5 properties: 42 Wallaby Way, 10 Bond St, 3 River Rd, 8 Park Ave, 15 Oak Lane." }, position: "right", actionLabel: "Next" },
    { id: "nav-reports", targetId: "reports-link", title: "6. Reports & Analytics", message: "Revenue by postcode, month-over-month growth, margins.", chatExample: { input: "How much did I earn last quarter?", output: "Q4 Revenue: $68,400. 42 jobs completed. Top suburb: Kensington ($18k)." }, position: "right", actionLabel: "Next" },
    { id: "reports-postcode", targetId: "reports-link", title: "Reports: Postcode Analysis", message: "See which areas generate the most revenue.", chatExample: { input: "Best performing suburbs this year?", output: "1. Kensington: $32k\n2. Paddington: $24k\n3. Surry Hills: $18k" }, position: "right", actionLabel: "Next" },
    { id: "nav-team", targetId: "team-link", title: "7. Team Management", message: "Manage subcontractors and employees. Assign them to jobs.", chatExample: { input: "Assign Ben to the Smith job", output: "Ben assigned to Smith Plumbing. He'll see: address, task list, safety form only." }, position: "right", actionLabel: "Next" },
    { id: "team-access", targetId: "team-link", title: "Team: Access Control", message: "Subbies see only what you allow — no pricing, no client lists.", chatExample: { input: "What can Ben see?", output: "Ben's access: Job address, task list, safety form. No pricing or contact details." }, position: "right", actionLabel: "Next" },
    { id: "nav-settings", targetId: "settings-link", title: "8. Workspace Settings", message: "Business profile, AI behavior, working hours, integrations.", chatExample: { input: "Open settings", output: "Navigating to Settings → Business Profile, AI Agent, Integrations." }, position: "right", actionLabel: "Next" },
    { id: "settings-ai", targetId: "settings-link", title: "Settings: AI Agent Config", message: "Control what your AI can do: Execute, Organize, or Filter mode.", chatExample: { input: "Set my AI to execute mode", output: "AI mode set to EXECUTE. I'll now handle jobs autonomously." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5: PIPELINE & KANBAN (Steps 56-75)
    // ══════════════════════════════════════════════════════════════
    { id: "pipeline-intro", targetId: "dashboard-link", title: "📊 Your Pipeline", message: "The Kanban board is your visual workflow. Every column is a stage.", chatExample: { input: "Show me my pipeline", output: "5 jobs: New Lead (1), Quoted (1), In Progress (2), Invoiced (1)." }, position: "right", actionLabel: "Next", section: "Pipeline" },
    { id: "pipeline-dragdrop", targetId: "dashboard-link", title: "Pipeline: Drag & Drop", message: "Move deals between stages visually, or just tell me.", chatExample: { input: "Move bathroom reno to scheduled", output: "\"Bathroom Reno\" moved from Quoted → Scheduled." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stale", targetId: "dashboard-link", title: "Pipeline: Stale Alerts", message: "Amber border = 7+ days without activity. Red = 14+ days (rotting).", chatExample: { input: "Show rotting deals", output: "1 rotting: Plumbing Fix ($4,500) — 16 days without activity." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-value", targetId: "dashboard-link", title: "Pipeline: Total Value", message: "See the dollar value sitting in each column.", chatExample: { input: "How much in quote sent?", output: "Quote Sent column: $28,000 across 3 deals." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-create", targetId: "new-deal-btn", title: "Pipeline: Create Deal", message: "Add jobs manually or through chat.", chatExample: { input: "New job Roof Repair for Anderson worth $6,500", output: "Job \"Roof Repair\" created for Anderson — $6,500. Added to New Lead." }, position: "bottom", actionLabel: "Next" },
    { id: "pipeline-stages-1", targetId: "dashboard-link", title: "Stage: New Lead", message: "Fresh enquiries land here. AI can auto-triage them.", chatExample: { input: "What new leads came in today?", output: "2 new leads today: Smith (plumbing) and Jones (electrical)." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stages-2", targetId: "dashboard-link", title: "Stage: Quoted", message: "Jobs you've sent a price estimate for.", chatExample: { input: "How many quotes are pending?", output: "4 quotes pending reply, total value: $32,000." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stages-3", targetId: "dashboard-link", title: "Stage: Scheduled", message: "Confirmed and booked into your calendar.", chatExample: { input: "What's scheduled this week?", output: "5 jobs this week: Mon (2), Tue (1), Thu (1), Fri (1)." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stages-4", targetId: "dashboard-link", title: "Stage: In Progress", message: "Jobs currently being worked on in the field.", chatExample: { input: "Which jobs are active right now?", output: "2 in progress: Deck Build (Williams) and Fence Repair (Brown)." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stages-5", targetId: "dashboard-link", title: "Stage: Invoiced", message: "Work done, invoice sent, waiting for payment.", chatExample: { input: "Outstanding invoices?", output: "3 unpaid invoices totaling $12,700. Oldest: 16 days (Davis Estate)." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-stages-6", targetId: "dashboard-link", title: "Stage: Completed / Paid", message: "Done and dusted. Revenue recorded.", chatExample: { input: "How many jobs completed this month?", output: "18 jobs completed in February. Total: $24,500." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-followup", targetId: "dashboard-link", title: "Pipeline: Auto Follow-up", message: "When a quote goes stale, I can auto-send a nudge.", chatExample: { input: "Follow up on all stale quotes", output: "Sending follow-up SMS to 3 clients with stale quotes..." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-filter", targetId: "dashboard-link", title: "Pipeline: Filters", message: "Filter by date, value, status, or client.", chatExample: { input: "Show jobs over $5,000", output: "3 jobs over $5k: Kitchen Reno ($28k), Bathroom ($12k), Deck ($8.5k)." }, position: "right", actionLabel: "Next" },
    { id: "pipeline-duplicate", targetId: "dashboard-link", title: "Pipeline: Duplicate Check", message: "I warn you if a similar job already exists for a client.", chatExample: { input: "New plumbing job for Davis", output: "⚠️ A similar job may already exist for Davis (Plumbing Fix, Invoiced)." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6: TRADIE FIELD WORKFLOW (Steps 76-105)
    // ══════════════════════════════════════════════════════════════
    { id: "tradie-intro", targetId: "map-link", title: "👷 Tradie Mode", message: "Mobile-first, map-centric interface designed for the field.", chatExample: { input: "Open tradie view", output: "Switching to Tradie Mode — map and job cards loaded." }, position: "right", actionLabel: "Next", section: "Tradie Mode" },
    { id: "tradie-map", targetId: "map-link", title: "Tradie: Job Map", message: "Interactive map showing all of today's jobs with color pins.", chatExample: { input: "Where's my next job?", output: "Next: Smith at 42 Oak St, Kensington. 12 min drive from your location." }, position: "right", actionLabel: "Next" },
    { id: "tradie-start-travel", targetId: "map-link", title: "Tradie: Start Travel", message: "Tap Start Travel to auto-SMS the client: 'I'm on my way. ETA 15 mins.'", chatExample: { input: "Start travel to Smith job", output: "Travel started. SMS sent to Smith: \"On my way, ETA 15 mins.\"" }, position: "right", actionLabel: "Next" },
    { id: "tradie-arrived", targetId: "map-link", title: "Tradie: Arrived", message: "Check in when you arrive. Status updates to ON_SITE.", chatExample: { input: "I've arrived at Smith's", output: "Checked in at Smith job. Status: On Site. Timer started." }, position: "right", actionLabel: "Next" },
    { id: "tradie-safety", targetId: "map-link", title: "Tradie: Safety Check", message: "Complete a risk assessment before starting work. Compliance-ready.", chatExample: { input: "Safety check complete", output: "Safety assessment logged. You're clear to begin work." }, position: "right", actionLabel: "Next" },
    { id: "tradie-complete", targetId: "map-link", title: "Tradie: Complete Job", message: "Mark done, trigger invoicing, and request a Google review.", chatExample: { input: "Complete the Smith job", output: "Job completed! Invoice generated. Review request SMS queued (2hr delay)." }, position: "right", actionLabel: "Next" },
    { id: "tradie-photos", targetId: "map-link", title: "Tradie: Before/After Photos", message: "Take photos directly to the job record.", chatExample: { input: "Add photos to Smith job", output: "Opening camera. Photos will attach to Smith job record." }, position: "right", actionLabel: "Next" },
    { id: "tradie-materials", targetId: "map-link", title: "Tradie: Material Picker", message: "Searchable parts database. Adds line items to the invoice.", chatExample: { input: "I used 2 copper elbows and 1 ball valve", output: "Added: 2x Copper Elbow ($12ea), 1x Ball Valve ($28). Total materials: $52." }, position: "right", actionLabel: "Next" },
    { id: "tradie-estimator", targetId: "map-link", title: "Tradie: Quick Estimator", message: "Generate Good/Better/Best quotes in seconds.", chatExample: { input: "Quick quote for bathroom reno", output: "3-tier quote:\nGood: $8,000 (basic)\nBetter: $12,000 (mid-range)\nBest: $18,000 (premium)" }, position: "right", actionLabel: "Next" },
    { id: "tradie-voice-diary", targetId: "voice-btn", title: "Tradie: Voice Diary", message: "Dictate job notes on-site instead of typing.", chatExample: { input: "🎤 \"Client has large dog, call before opening gate\"", output: "Note saved to job: \"Client has large dog, call before opening gate.\"" }, position: "left", actionLabel: "Next" },
    { id: "tradie-invoice", targetId: "map-link", title: "Tradie: One-Tap Invoice", message: "Generate PDF invoice from materials + labor logged.", chatExample: { input: "Invoice Smith for 2hrs labor plus materials", output: "Invoice: 2hr labor ($160) + materials ($52) = $212 inc GST $233.20." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 7: COMMUNICATION FEATURES (Steps 106-130)
    // ══════════════════════════════════════════════════════════════
    { id: "comms-intro", targetId: "inbox-link", title: "📱 Communications Hub", message: "SMS, Email, Calls — all managed from one place.", chatExample: { input: "Show my recent messages", output: "Last 5: Steven (SMS), Mary (Email), John (Call transcript)..." }, position: "right", actionLabel: "Next", section: "Communications" },
    { id: "comms-sms-auto", targetId: "inbox-link", title: "Auto SMS Triggers", message: "Automatic texts on job status changes.", chatExample: { input: "What auto-texts are set up?", output: "Active triggers: Start Travel → ETA SMS, Job Complete → Review request." }, position: "right", actionLabel: "Next" },
    { id: "comms-sms-template", targetId: "inbox-link", title: "SMS Templates", message: "Pre-built message templates for common situations.", chatExample: { input: "Send rainy day special to past clients", output: "Campaign: \"Rainy day indoor special\" sent to 12 qualified contacts." }, position: "right", actionLabel: "Next" },
    { id: "comms-sms-bulk", targetId: "inbox-link", title: "Bulk Messaging", message: "Send campaigns to filtered contact lists.", chatExample: { input: "Text all afternoon clients I'm running 30 mins late", output: "SMS sent to 3 afternoon clients: \"Running 30 mins behind schedule.\"" }, position: "right", actionLabel: "Next" },
    { id: "comms-email-draft", targetId: "inbox-link", title: "Email Drafting", message: "AI drafts professional emails for you.", chatExample: { input: "Draft email to John about delayed parts", output: "Draft: \"Hi John, the valve is backordered. New ETA Thursday. I'll call to rebook.\"" }, position: "right", actionLabel: "Next" },
    { id: "comms-call-ai", targetId: "inbox-link", title: "AI Voice Agent", message: "Your AI answers calls, takes messages, and routes emergencies.", chatExample: { input: "Set up after-hours mode", output: "After-hours active 5pm-8am. Routine → voicemail, Emergency → patch through." }, position: "right", actionLabel: "Next" },
    { id: "comms-call-outbound", targetId: "inbox-link", title: "Outbound Calls", message: "Initiate calls through the AI voice agent.", chatExample: { input: "Call Mary about the kitchen quote", output: "Calling Mary (0412 345 678). Purpose: Kitchen quote follow-up." }, position: "right", actionLabel: "Next" },
    { id: "comms-history", targetId: "inbox-link", title: "Conversation History", message: "Full timeline of all interactions per contact.", chatExample: { input: "Show me history with Steven", output: "Steven: 12 texts, 3 calls, 2 emails over 4 months. Last: yesterday." }, position: "right", actionLabel: "Next" },
    { id: "comms-missed-call", targetId: "inbox-link", title: "Missed Call Rescue", message: "AI handles missed calls, texts the client, logs everything.", chatExample: { input: "Any missed calls today?", output: "1 missed: 0412 567 890 (Unknown). AI sent intro SMS, waiting for reply." }, position: "right", actionLabel: "Next" },
    { id: "comms-confirmation", targetId: "inbox-link", title: "Auto Confirmations", message: "24hr before, I send confirmation SMS to clients.", chatExample: { input: "Did Wendy confirm for tomorrow?", output: "Wendy: Confirmation sent 2h ago. Status: No reply yet." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 8: SCHEDULING & ROUTING (Steps 131-150)
    // ══════════════════════════════════════════════════════════════
    { id: "sched-intro", targetId: "schedule-link", title: "📅 Smart Scheduling", message: "AI-powered calendar with conflict detection and routing.", chatExample: { input: "What's my week look like?", output: "Mon: 3 jobs, Tue: 2, Wed: free, Thu: 4, Fri: 1. Revenue forecast: $4,200." }, position: "right", actionLabel: "Next", section: "Scheduling" },
    { id: "sched-availability", targetId: "schedule-link", title: "Check Availability", message: "Find open slots on any day.", chatExample: { input: "Am I free Tuesday afternoon?", output: "Tuesday PM: Free 1pm-5pm. Closest job: 10am in Kensington." }, position: "right", actionLabel: "Next" },
    { id: "sched-reschedule", targetId: "schedule-link", title: "Reschedule Jobs", message: "Move jobs to new times with one command.", chatExample: { input: "Reschedule Wendy to Friday 10am", output: "Wendy moved to Friday 10am. Confirmation SMS sent." }, position: "right", actionLabel: "Next" },
    { id: "sched-cancel", targetId: "schedule-link", title: "Cancel & Waitlist", message: "Cancel a job and auto-offer the slot to waitlisted clients.", chatExample: { input: "Cancel Monday's 2pm job", output: "Cancelled. Checking waitlist... Mrs. Jones wants a Monday slot. Offering now." }, position: "right", actionLabel: "Next" },
    { id: "sched-block", targetId: "schedule-link", title: "Block Time", message: "Block out personal time or maintenance windows.", chatExample: { input: "Block Wednesday morning for van service", output: "Wednesday AM blocked: \"Van service\". No jobs will be scheduled." }, position: "right", actionLabel: "Next" },
    { id: "sched-proximity", targetId: "schedule-link", title: "Proximity Scheduling", message: "I group nearby jobs to minimize driving.", chatExample: { input: "Any clients near my 2pm job?", output: "3 past clients within 2km: Jones (service due), Smith (follow-up), Brown." }, position: "right", actionLabel: "Next" },
    { id: "sched-emergency", targetId: "schedule-link", title: "Emergency Reschedule", message: "Van broke down? I'll contact all affected clients.", chatExample: { input: "Emergency: van broke down, reschedule all today", output: "Contacting 5 clients. Proposing tomorrow slots. 3 auto-accepted so far." }, position: "right", actionLabel: "Next" },
    { id: "sched-delay", targetId: "schedule-link", title: "Running Late Alert", message: "Notify all affected clients with one command.", chatExample: { input: "Running 30 mins late", output: "SMS sent to remaining 2 afternoon clients: \"Running 30 mins behind.\"" }, position: "right", actionLabel: "Next" },
    { id: "sched-optimal", targetId: "schedule-link", title: "Optimal Route", message: "I suggest the best order for your day's jobs.", chatExample: { input: "Plan my route for tomorrow", output: "Optimal order: 8am Smith (Syd), 10am Jones (2km), 1pm Davis (5km). Total: 12km." }, position: "right", actionLabel: "Next" },
    { id: "sched-gaps", targetId: "schedule-link", title: "Fill Empty Slots", message: "Use the /fill-my-day command to fill gaps.", chatExample: { input: "Fill my empty afternoon", output: "Found 8 clients nearby due for service. Sending \"availability\" texts now." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 9: PRICING & QUOTING (Steps 151-165)
    // ══════════════════════════════════════════════════════════════
    { id: "pricing-intro", targetId: "settings-link", title: "💲 Pricing & Quoting", message: "Set your call-out fee, pricing range, and let AI quote for you.", chatExample: { input: "What's my call-out fee?", output: "Your call-out fee is $120. Top 3 services: Tap repair ($80-180), Drain clear ($150-350), HWS install ($800-2,500)." }, position: "right", actionLabel: "Next", section: "Pricing" },
    { id: "pricing-callout", targetId: "settings-link", title: "Pricing: Call-Out Fee", message: "Your base fee for showing up. Default $0.", chatExample: { input: "Set call-out fee to $120", output: "Call-out fee updated to $120." }, position: "right", actionLabel: "Next" },
    { id: "pricing-range", targetId: "settings-link", title: "Pricing: Typical Range", message: "Set price ranges for your common services.", chatExample: { input: "Typical price for tap repair is $80 to $180", output: "Price range saved: Tap Repair $80-$180." }, position: "right", actionLabel: "Next" },
    { id: "pricing-quote-gen", targetId: "chat-input", title: "Pricing: AI Quoting", message: "I can generate quotes based on your pricing rules.", chatExample: { input: "Quote blocked drain for Mary", output: "Based on your pricing: Blocked drain $150-$350. Call-out fee: $120. Shall I send?" }, position: "left", actionLabel: "Next" },
    { id: "pricing-margin", targetId: "chat-input", title: "Pricing: Margin Check", message: "Quick margin calculations on the fly.", chatExample: { input: "Materials $400, labor $300, what do I charge for 40% margin?", output: "Charge $1,167 for 40% gross margin (materials $400 + labor $300 = $700 cost)." }, position: "left", actionLabel: "Next" },
    { id: "pricing-gst", targetId: "chat-input", title: "Pricing: GST Calculator", message: "Quick tax math.", chatExample: { input: "What's $1,250 plus GST?", output: "$1,250 + 10% GST = $1,375.00" }, position: "left", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 10: AI AGENT MODES (Steps 166-175)
    // ══════════════════════════════════════════════════════════════
    { id: "agent-intro", targetId: "settings-link", title: "🤖 AI Agent Modes", message: "Control how autonomous your AI is.", chatExample: { input: "What mode is my AI in?", output: "Current mode: ORGANIZE. I propose actions and wait for your approval." }, position: "right", actionLabel: "Next", section: "AI Agent" },
    { id: "agent-execute", targetId: "settings-link", title: "Mode: Execute", message: "Full autonomy. AI schedules, prices, and creates jobs independently.", chatExample: { input: "Set AI to execute mode", output: "Execute mode ON. I'll handle jobs, pricing, and scheduling autonomously." }, position: "right", actionLabel: "Next" },
    { id: "agent-organize", targetId: "settings-link", title: "Mode: Organize", message: "AI proposes, you approve. Draft cards appear for confirmation.", chatExample: { input: "Set AI to organize mode", output: "Organize mode ON. I'll propose actions and wait for your confirmation." }, position: "right", actionLabel: "Next" },
    { id: "agent-filter", targetId: "settings-link", title: "Mode: Filter", message: "Screening only. AI collects info but takes no action.", chatExample: { input: "Set AI to filter mode", output: "Filter mode ON. I'll screen and collect info, but not schedule or price." }, position: "right", actionLabel: "Next" },
    { id: "agent-afterhours", targetId: "settings-link", title: "After-Hours Agent", message: "AI answers calls after hours, takes messages, routes emergencies.", chatExample: { input: "Set after hours 5pm to 8am", output: "After-hours active 5pm-8am. Routine calls → voicemail. Emergency → ring you." }, position: "right", actionLabel: "Next" },
    { id: "agent-spam", targetId: "settings-link", title: "Spam Filter", message: "AI screens unknown callers so you never answer spam.", chatExample: { input: "Block spam calls", output: "Spam screening ON. Unknown callers go to AI first. Real clients get through." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 11: CRM & CONTACTS (Steps 176-190)
    // ══════════════════════════════════════════════════════════════
    { id: "crm-intro", targetId: "contacts-link", title: "👥 CRM Intelligence", message: "Your contacts are auto-enriched with job history and preferences.", chatExample: { input: "How many contacts do I have?", output: "142 contacts. 38 active clients, 12 VIPs, 92 past clients." }, position: "right", actionLabel: "Next", section: "CRM" },
    { id: "crm-vip", targetId: "contacts-link", title: "CRM: VIP Clients", message: "Tag high-value repeat clients as VIPs.", chatExample: { input: "Tag Jane Smith as VIP", output: "Jane Smith tagged VIP. She'll get priority routing and response." }, position: "right", actionLabel: "Next" },
    { id: "crm-service-due", targetId: "contacts-link", title: "CRM: Service Due", message: "Automatic reminders for annual services and warranties.", chatExample: { input: "Who's due for annual service?", output: "5 clients due: Smith (AC, 11mo), Jones (HWS, 10mo)..." }, position: "right", actionLabel: "Next" },
    { id: "crm-warranty", targetId: "contacts-link", title: "CRM: Warranty Watch", message: "Track warranties and alert before expiry.", chatExample: { input: "Any warranties expiring soon?", output: "2 warranties expiring: Smith HWS (next month), Jones AC (2 months)." }, position: "right", actionLabel: "Next" },
    { id: "crm-winback", targetId: "contacts-link", title: "CRM: Win-Back Campaigns", message: "Re-engage dormant clients with targeted outreach.", chatExample: { input: "Find clients I haven't seen in 2 years", output: "50 contacts found. Shall I send a win-back campaign?" }, position: "right", actionLabel: "Next" },
    { id: "crm-search-fuzzy", targetId: "contacts-link", title: "CRM: Fuzzy Search", message: "Even partial names work. Type 'Joh' to find John.", chatExample: { input: "Find Thom", output: "Found: Sarah Thompson (0412 345 678), Thomas Williams (0423 456 789)." }, position: "right", actionLabel: "Next" },
    { id: "crm-bulk", targetId: "contacts-link", title: "CRM: Bulk Actions", message: "Select multiple contacts for campaigns.", chatExample: { input: "Send service reminders to all overdue clients", output: "Sending \"Annual service due\" SMS to 5 clients..." }, position: "right", actionLabel: "Next" },
    { id: "crm-ltv", targetId: "contacts-link", title: "CRM: Lifetime Value", message: "Track how much each client has spent with you.", chatExample: { input: "Who are my top 5 clients?", output: "1. Jane Smith: $15k\n2. John Doe: $12k\n3. Mary Brown: $8k..." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 12: KEYBOARD SHORTCUTS & TIPS (Steps 191-195)
    // ══════════════════════════════════════════════════════════════
    { id: "shortcut-cmdk", targetId: "search-btn", title: "⌨️ Cmd+K — Command Palette", message: "The fastest way to navigate. Search anything.", chatExample: { input: "Press Ctrl+K then type \"Smith\"", output: "Results: John Smith (contact), Smith Plumbing (job), Smith Invoice..." }, position: "bottom", actionLabel: "Next", section: "Shortcuts" },
    { id: "shortcut-slash", targetId: "chat-input", title: "⌨️ / — Focus Chat", message: "Press / to jump to the chat input from anywhere.", chatExample: { input: "Press / then type your command", output: "Chat input focused. Type away!" }, position: "left", actionLabel: "Next" },
    { id: "shortcut-esc", targetId: null, title: "⌨️ Esc — Close Anything", message: "Press Escape to close modals, panels, and overlays.", actionLabel: "Next" },
    { id: "shortcut-undo", targetId: "chat-input", title: "⌨️ Undo Actions", message: "Made a mistake? Just say undo.", chatExample: { input: "Undo that", output: "Last action reversed: \"Move Bathroom Reno to Completed\" → back to In Progress." }, position: "left", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 13: ADVANCED CHAT COMMANDS (Steps 121-135)
    // ══════════════════════════════════════════════════════════════
    { id: "adv-draft", targetId: "chat-input", title: "⚡ /draft Command", message: "Create a new job/deal from a prompt without scheduling it.", chatExample: { input: "/draft new quote for Sarah's kitchen $4,500", output: "Draft created: Kitchen Quote for Sarah — $4,500. Not yet scheduled." }, position: "left", actionLabel: "Next", section: "Power Commands" },
    { id: "adv-summarize", targetId: "chat-input", title: "⚡ /summarize Command", message: "Summarize the current view — a thread, a job, or a client.", chatExample: { input: "/summarize", output: "Job Summary: Smith Plumbing — 3 visits, $1,200 total. Last: pipe replaced." }, position: "left", actionLabel: "Next" },
    { id: "adv-fillday", targetId: "chat-input", title: "⚡ /fill-my-day Command", message: "Find work to fill empty slots.", chatExample: { input: "/fill-my-day", output: "Found 20 clients due for service near your route. Sending availability texts." }, position: "left", actionLabel: "Next" },
    { id: "adv-winback-cmd", targetId: "chat-input", title: "⚡ /marketing win-back", message: "Re-engage dormant contacts.", chatExample: { input: "/marketing win-back", output: "50 clients haven't booked in 24+ months. Campaign: \"We miss you...\" Ready?" }, position: "left", actionLabel: "Next" },
    { id: "adv-conversion", targetId: "chat-input", title: "Unit Conversions", message: "Quick imperial/metric conversions.", chatExample: { input: "Convert 1.5 inches to millimeters", output: "1.5 inches = 38.1 mm" }, position: "left", actionLabel: "Next" },
    { id: "adv-tile-calc", targetId: "chat-input", title: "Material Calculations", message: "Calculate materials with wastage.", chatExample: { input: "Tile a 4m x 5m room with 10% wastage", output: "You need 22 sqm of tiles (20 sqm + 10% wastage)." }, position: "left", actionLabel: "Next" },
    { id: "adv-code-check", targetId: "chat-input", title: "Code & Compliance", message: "Look up Australian building codes.", chatExample: { input: "Standard clearance for gas cooktop?", output: "AS/NZS 5601: Min 600mm to combustible surfaces above, 200mm to sides." }, position: "left", actionLabel: "Next" },
    { id: "adv-error-codes", targetId: "chat-input", title: "Error Code Lookup", message: "Troubleshoot equipment issues.", chatExample: { input: "Daikin error code E4", output: "E4: Low pressure fault. Check: refrigerant charge, outdoor fan, filter blockage." }, position: "left", actionLabel: "Next" },
    { id: "adv-safety-checklist", targetId: "chat-input", title: "Generate Checklists", message: "Create work-specific safety checklists.", chatExample: { input: "Safety checklist for scissor lift", output: "1. Pre-use inspection\n2. Ground conditions\n3. Guardrails\n4. Emergency stop\n5. PPE" }, position: "left", actionLabel: "Next" },
    { id: "adv-tool-list", targetId: "chat-input", title: "Tool Requirements", message: "Know what tools you need before arriving.", chatExample: { input: "Tools for bleeding hydronic heating", output: "Needed: Bleed key, container, towels, pressure gauge, hose." }, position: "left", actionLabel: "Next" },
    { id: "adv-reply-suggest", targetId: "chat-input", title: "Reply Suggestions", message: "AI suggests responses to tricky messages.", chatExample: { input: "Suggest reply to customer complaining about price", output: "\"I understand the concern. Our pricing includes [warranty/quality]. Shall I break down the costs?\"" }, position: "left", actionLabel: "Next" },
    { id: "adv-translate", targetId: "chat-input", title: "Quick Translation", message: "Translate messages for multicultural clients.", chatExample: { input: "Translate 'Water off for 2 hours' to Mandarin", output: "停水两小时 (Tíng shuǐ liǎng xiǎoshí)" }, position: "left", actionLabel: "Next" },
    { id: "adv-purchase", targetId: "chat-input", title: "Purchase Logging", message: "Track expenses on the go.", chatExample: { input: "Spent $150 at Bunnings on PVC glue and fittings", output: "Expense logged: $150 — Bunnings — PVC glue & fittings. Tagged to active job." }, position: "left", actionLabel: "Next" },
    { id: "adv-switch-light", targetId: "chat-input", title: "App Appearance", message: "Toggle light/dark mode.", chatExample: { input: "Switch to dark mode", output: "Dark mode activated." }, position: "left", actionLabel: "Next" },
    { id: "adv-signout", targetId: "chat-input", title: "Sign Out via Chat", message: "Even signing out works from chat.", chatExample: { input: "Log me out", output: "Signing out... See you next time!" }, position: "left", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 14: USE CASE WALKTHROUGHS (Steps 136-155)
    // ══════════════════════════════════════════════════════════════
    { id: "uc-missed-call", targetId: "inbox-link", title: "📖 Missed Call Rescue", message: "You're driving, miss a call. AI auto-texts the client, qualifies the lead, logs everything.", chatExample: { input: "Any missed calls?", output: "1 missed: 0412 345 678. AI sent: \"Thanks for calling. A plumbing emergency? Reply YES.\"" }, position: "right", actionLabel: "Next", section: "Use Cases" },
    { id: "uc-rainy-day", targetId: "chat-input", title: "📖 Rainy Day Reactivation", message: "3 outdoor jobs cancelled. Fill your day with indoor work.", chatExample: { input: "It's raining. Find me indoor work", output: "12 past clients in your area due for heater service. Send campaign?" }, position: "left", actionLabel: "Next" },
    { id: "uc-tire-kicker", targetId: "chat-input", title: "📖 Tire Kicker Filter", message: "Web enquiry comes in. AI auto-replies and asks for photos to qualify.", chatExample: { input: "New web enquiry from Smith about switchboard", output: "AI auto-replied requesting photo. If asbestos detected, I'll flag as hazard." }, position: "left", actionLabel: "Next" },
    { id: "uc-pre-arrival", targetId: "map-link", title: "📖 Pre-Arrival Prep", message: "1 hour before a job, AI texts the client to prepare.", chatExample: { input: "Remind next client to clear driveway", output: "SMS sent: \"Hi, Mike will be there in ~1 hour. Please ensure clear access.\"" }, position: "right", actionLabel: "Next" },
    { id: "uc-no-show", targetId: "schedule-link", title: "📖 No-Show Prevention", message: "24hr confirmation SMS auto-sent. Reschedule if client can't make it.", chatExample: { input: "Did all tomorrow's clients confirm?", output: "3 confirmed ✅, 1 no reply ⚠️ (Jones 10am). Want me to send a nudge?" }, position: "right", actionLabel: "Next" },
    { id: "uc-ghost-quote", targetId: "dashboard-link", title: "📖 Ghosted Quote Chase", message: "Quote sent 2 weeks ago, no reply. AI sends a nurture message.", chatExample: { input: "Chase the bathroom reno quote", output: "SMS sent: \"Hi, just checking in on the bathroom quote. I'm finalizing my schedule...\"" }, position: "right", actionLabel: "Next" },
    { id: "uc-review", targetId: "chat-input", title: "📖 Review Chasing", message: "Job complete. AI sends Google Review link 2 hours later.", chatExample: { input: "Send review request to last client", output: "SMS queued (2hr delay): \"If you have 2 seconds, a review really helps. [Google Link]\"" }, position: "left", actionLabel: "Next" },
    { id: "uc-retention", targetId: "contacts-link", title: "📖 Annual Retention", message: "11 months after install, AI flags maintenance due.", chatExample: { input: "Who needs annual service?", output: "5 clients: AC service (Smith), HWS check (Jones), Heater tune-up (Brown)..." }, position: "right", actionLabel: "Next" },
    { id: "uc-handover", targetId: "chat-input", title: "📖 Digital Handover", message: "After install, send a handover pack with manuals and video.", chatExample: { input: "Send handover pack for thermostat install", output: "Handover email sent with Daikin manual PDF and your 60-second explainer video." }, position: "left", actionLabel: "Next" },
    { id: "uc-bad-review", targetId: "chat-input", title: "📖 Bad Review Firewall", message: "AI asks for satisfaction score BEFORE they hit Google.", chatExample: { input: "Send feedback request to Jones", output: "SMS sent: \"On a scale of 1-10, how happy were you?\" Score < 8 = private resolution." }, position: "left", actionLabel: "Next" },
    { id: "uc-uber-arrival", targetId: "map-link", title: "📖 Uber-Style Tracking", message: "Client receives a live tracking link when you start travel.", chatExample: { input: "Start travel to Wendy's job", output: "SMS sent with live tracking link. Client can see your ETA on a map." }, position: "right", actionLabel: "Next" },
    { id: "uc-vip-fastlane", targetId: "contacts-link", title: "📖 VIP Fast-Lane", message: "Property managers get auto-booking without approval.", chatExample: { input: "Set up VIP auto-booking for Jane", output: "VIP mode ON for Jane. Her texts auto-create jobs. No approval needed." }, position: "right", actionLabel: "Next" },
    { id: "uc-daily-digest", targetId: "chat-input", title: "📖 Daily Project Update", message: "Send photo updates to clients during multi-day jobs.", chatExample: { input: "Send day 2 update to Smith with 3 photos", output: "Project update sent: \"Day 2: Waterproofing complete. Tiles arriving tomorrow.\"" }, position: "left", actionLabel: "Next" },
    { id: "uc-parts-watch", targetId: "inbox-link", title: "📖 Parts Tracking", message: "AI parses supplier emails and auto-notifies clients.", chatExample: { input: "Any parts shipped today?", output: "Supplier email: Order #999 shipped. Auto-SMS to client: \"Part arriving Thursday.\"" }, position: "right", actionLabel: "Next" },
    { id: "uc-compliance", targetId: "chat-input", title: "📖 Compliance Pack", message: "Auto-send insurance and licence docs when requested.", chatExample: { input: "Send compliance pack to new strata client", output: "Email sent with: Public Liability, Workers Comp, and Plumbing Licence attached." }, position: "left", actionLabel: "Next" },
    { id: "uc-hold-buster", targetId: "dashboard-link", title: "📖 Hold Buster", message: "Stuck jobs? AI nudges clients to move forward.", chatExample: { input: "Chase all pending jobs", output: "3 jobs in 'Waiting on Client' > 7d. SMS sent: \"Have those tiles arrived yet?\"" }, position: "right", actionLabel: "Next" },
    { id: "uc-neighbourhood", targetId: "map-link", title: "📖 Neighbourhood Batch", message: "Finished early? Find nearby past clients.", chatExample: { input: "Any clients nearby with pending work?", output: "2 clients within 1km with pending items. Sending \"nearby\" offer now." }, position: "right", actionLabel: "Next" },
    { id: "uc-lead-source", targetId: "reports-link", title: "📖 Lead Source ROI", message: "Track which marketing channels work.", chatExample: { input: "Where do my best leads come from?", output: "Google Ads: 12 leads → $28k revenue. Facebook: 8 leads → $3k. Word of mouth: $45k." }, position: "right", actionLabel: "Next" },
    { id: "uc-subbie", targetId: "team-link", title: "📖 Subbie Management", message: "Assign jobs to subbies with restricted view.", chatExample: { input: "Assign next 3 jobs to Ben", output: "3 jobs assigned to Ben. View: task list & address only. No pricing visible." }, position: "right", actionLabel: "Next" },
    { id: "uc-smart-resched", targetId: "schedule-link", title: "📖 Smart Reschedule", message: "Emergency? AI contacts all clients in one command.", chatExample: { input: "Van broke down, reschedule today", output: "5 clients notified. 3 auto-accepted tomorrow slots. 2 waiting for reply." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 15: ACTIVITY FEED & INTEGRATIONS (Steps 156-170)
    // ══════════════════════════════════════════════════════════════
    { id: "activity-intro", targetId: "dashboard-link", title: "📜 Activity Feed", message: "Unified timeline of all interactions for every deal.", chatExample: { input: "Show activity for Smith job", output: "Timeline: SMS sent, Call (3 min), Quote sent ($450), Status → Scheduled." }, position: "right", actionLabel: "Next", section: "Activity & Integrations" },
    { id: "activity-events", targetId: "dashboard-link", title: "Activity: Event Types", message: "Emails, calls, SMS, notes, status changes — all logged.", chatExample: { input: "What happened with Johnson deal this week?", output: "3 events: Email reply (Mon), Call (Wed, 5 min), Quote updated (Thu)." }, position: "right", actionLabel: "Next" },
    { id: "activity-media", targetId: "dashboard-link", title: "Activity: Rich Media", message: "Email snippets and voice note transcriptions in the feed.", chatExample: { input: "Show the email from Johnson", output: "Email snippet: \"Hi, we'd like to proceed with Option B. Can you start next week?\"" }, position: "right", actionLabel: "Next" },
    { id: "int-calendar", targetId: "settings-link", title: "📅 Calendar Sync", message: "Two-way sync with Google Calendar and Outlook.", chatExample: { input: "Sync my Google Calendar", output: "Google Calendar connected. 12 events imported. Two-way sync active." }, position: "right", actionLabel: "Next" },
    { id: "int-offline", targetId: null, title: "📶 Offline Support", message: "No signal? The app works offline and syncs when you're back.", actionLabel: "Next" },
    { id: "int-storage", targetId: "settings-link", title: "☁️ Cloud Storage", message: "Photos, invoices, and documents stored securely in the cloud.", chatExample: { input: "How much storage am I using?", output: "Storage: 2.4 GB of 10 GB used. 156 photos, 42 invoices, 8 documents." }, position: "right", actionLabel: "Next" },
    { id: "int-stripe", targetId: "settings-link", title: "💳 Stripe Integration", message: "Accept payments directly through the app.", chatExample: { input: "Send payment link to Johnson", output: "Stripe payment link sent: $4,500 for Kitchen Reno. Expires in 7 days." }, position: "right", actionLabel: "Next" },
    { id: "int-whatsapp", targetId: "settings-link", title: "💬 WhatsApp (Agent Mode)", message: "For Real Estate agents: send reports via WhatsApp.", chatExample: { input: "Send vendor report via WhatsApp", output: "WhatsApp message sent to vendor with feedback summary and price guide." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 16: REAL ESTATE AGENT MODE (Steps 171-180)
    // ══════════════════════════════════════════════════════════════
    { id: "agent-re-intro", targetId: null, title: "🏠 Agent Mode (Real Estate)", message: "Pj Buddy also works for Real Estate agents with specialized tools.", actionLabel: "Next", section: "Real Estate" },
    { id: "agent-re-speed", targetId: "kpi-cards", title: "Agent: Speed-to-Lead", message: "Track how fast you respond to new enquiries.", chatExample: { input: "What's my average response time?", output: "Average response: 4.2 minutes. Goal: < 5 mins. You're on track! ✅" }, position: "bottom", actionLabel: "Next" },
    { id: "agent-re-vendor", targetId: "reports-link", title: "Agent: Vendor Reports", message: "Automated feedback reports from open houses.", chatExample: { input: "Generate vendor report for 42 Oak St", output: "Report: 18 inspections, 4 interested buyers. Feedback range: $800k-$950k." }, position: "right", actionLabel: "Next" },
    { id: "agent-re-commission", targetId: "reports-link", title: "Agent: Commission Calculator", message: "Forecast earnings from pipeline value.", chatExample: { input: "Project my commission this quarter", output: "Pipeline: $2.4M. At 2.5% commission: $60,000 potential earnings." }, position: "right", actionLabel: "Next" },
    { id: "agent-re-match", targetId: "contacts-link", title: "Agent: Matchmaker", message: "AI matches buyers to listings by budget, location, preferences.", chatExample: { input: "Find buyers for 42 Oak St listing", output: "3 matches: Johnson (budget $900k), Smith (budget $850k), Brown (budget $950k)." }, position: "right", actionLabel: "Next" },
    { id: "agent-re-kiosk", targetId: null, title: "🖥️ Kiosk Mode", message: "Tablet mode for open house visitor registration. QR code entry.", actionLabel: "Next" },
    { id: "agent-re-kiosk-qr", targetId: null, title: "Kiosk: QR Registration", message: "Visitors scan QR to register on their phone. Auto-syncs to your CRM.", actionLabel: "Next" },
    { id: "agent-re-pipeline", targetId: "dashboard-link", title: "Agent: Pipeline Stages", message: "Different stages for Real Estate: Appraisal, Listed, Under Offer, Exchanged, Settled.", chatExample: { input: "Show my real estate pipeline", output: "Pipeline: Appraisal (3), Listed (5), Under Offer (2), Exchanged (1)." }, position: "right", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 17: MARKETING & OUTREACH (Steps 181-190)
    // ══════════════════════════════════════════════════════════════
    { id: "mkt-intro", targetId: "contacts-link", title: "📣 Marketing Automation", message: "Turn your CRM into a marketing machine.", chatExample: { input: "How many marketing campaigns have I sent?", output: "12 campaigns this year. Best performer: \"Rainy Day Special\" (18% response rate)." }, position: "right", actionLabel: "Next", section: "Marketing" },
    { id: "mkt-seasonal", targetId: "chat-input", title: "Seasonal Campaigns", message: "Pre-summer AC checks, pre-winter heater service.", chatExample: { input: "Send pre-summer AC check campaign", output: "Campaign: \"Summer is coming! Book your AC service.\" Sent to 35 eligible clients." }, position: "left", actionLabel: "Next" },
    { id: "mkt-referral", targetId: "chat-input", title: "Referral Requests", message: "Ask happy clients for referrals.", chatExample: { input: "Send referral request to last 5 completed jobs", output: "SMS sent: \"Know anyone who needs a tradie? Refer a friend and get $50 off!\"" }, position: "left", actionLabel: "Next" },
    { id: "mkt-promo", targetId: "chat-input", title: "Promotional Offers", message: "Create time-limited offers.", chatExample: { input: "Create 10% off promotion for this week", output: "Promo created: \"10% off all services this week.\" Ready to send to 48 contacts." }, position: "left", actionLabel: "Next" },
    { id: "mkt-birthday", targetId: "contacts-link", title: "Birthday/Anniversary", message: "Auto-send greetings to build relationships.", chatExample: { input: "Any client birthdays this month?", output: "3 birthdays: Smith (15th), Jones (22nd), Brown (28th). Send greetings?" }, position: "right", actionLabel: "Next" },
    { id: "mkt-testimonial", targetId: "chat-input", title: "Testimonial Collection", message: "Collect and showcase client testimonials.", chatExample: { input: "Request testimonial from Johnson", output: "Email sent requesting testimonial. If approved, added to your showcase page." }, position: "left", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 18: BONUS FEATURES (Steps 184-193)
    // ══════════════════════════════════════════════════════════════
    { id: "bonus-security", targetId: "settings-link", title: "🔐 Data Security", message: "Your data is encrypted and stored in Australia. SOC2 compliant.", chatExample: { input: "Is my data secure?", output: "All data encrypted at rest & in transit. Hosted in Sydney (AU). SOC2 compliant." }, position: "right", actionLabel: "Next", section: "Bonus Features" },
    { id: "bonus-mobile", targetId: null, title: "📱 Mobile Experience", message: "Pj Buddy is fully responsive. Use it on your phone in the field — same features, touch-optimised.", actionLabel: "Next" },
    { id: "bonus-smart-notif", targetId: "notifications-btn", title: "🔔 Smart Notifications", message: "I only ping you for important things. Noise is filtered.", chatExample: { input: "Mute non-urgent notifications", output: "Non-urgent notifications muted. You'll only see: payments, emergencies, client replies." }, position: "bottom", actionLabel: "Next" },
    { id: "bonus-invoice-track", targetId: "dashboard-link", title: "💸 Invoice Tracking", message: "See all outstanding invoices and payment status in one view.", chatExample: { input: "Show overdue invoices", output: "2 overdue: Smith ($450, 14 days), Davis ($2,100, 21 days). Send reminders?" }, position: "right", actionLabel: "Next" },
    { id: "bonus-booking-link", targetId: "chat-input", title: "🔗 Booking Links", message: "Share a self-service booking link with clients.", chatExample: { input: "Send booking link to Johnson", output: "Booking link sent. Johnson can select available slots and book directly." }, position: "left", actionLabel: "Next" },
    { id: "bonus-review-mgmt", targetId: "chat-input", title: "⭐ Review Management", message: "Track and respond to Google reviews from the app.", chatExample: { input: "Show my Google reviews", output: "4.8★ average (42 reviews). 2 new this week. 1 needs a response." }, position: "left", actionLabel: "Next" },
    { id: "bonus-data-export", targetId: "settings-link", title: "📤 Data Export", message: "Export your contacts, jobs, and financials anytime.", chatExample: { input: "Export my contacts to CSV", output: "CSV exported: 142 contacts with full details. Download link ready." }, position: "right", actionLabel: "Next" },
    { id: "bonus-competitive", targetId: null, title: "🏆 Competitive Edge", message: "95% of tradies don't follow up. 80% don't track leads. You're already ahead by using Pj Buddy.", actionLabel: "Next" },
    { id: "bonus-pro-tip", targetId: "chat-input", title: "💡 Pro Tip", message: "The #1 most powerful thing you can do? Talk to me every morning. Say 'What's on today?' and I'll set you up for success.", chatExample: { input: "What's on today?", output: "Good morning! 4 jobs today totaling $3,200. First up: Smith at 8am (15 min drive)." }, position: "left", actionLabel: "Next" },
    { id: "bonus-feedback", targetId: null, title: "💬 We're Listening", message: "Found something that could be better? Just type 'feedback' in chat and tell us. We read every message.", actionLabel: "Next" },

    // ══════════════════════════════════════════════════════════════
    // SECTION 19: WRAP UP (Final Steps)
    // ══════════════════════════════════════════════════════════════
    { id: "replay", targetId: null, title: "🔄 Replay Anytime", message: "You can replay this tutorial from Settings → Help at any time.", actionLabel: "Next", section: "Wrap Up" },
    { id: "finish", targetId: null, title: "You're Ready to Roll! 🚀", message: "That's everything! To get started, try asking me:\n\n📱 \"Create a new test job\"\n📱 \"What's on my schedule?\"\n📱 \"Show me my pipeline\"\n\nI'm always here to help. Let's build your business together!", actionLabel: "Start Using Pj Buddy" },
]
